import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { cn } from "@/utils/lib/tailwind";
import Header from "@/components/layout/header";

const inter = Inter({ subsets: ['latin'], variable: "--font-sans", });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl">
			<body className={cn(
				'min-h-screen bg-foreground font-sans antialiased',
				inter.variable
			)}>
				<Header />
				<main>
				{children}
				</main>
			</body>
		</html>
	);
}
